name: Deploy Leasing to leasing.sergeivbo.ru

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bump version and push tag
        id: bump_version
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: 'v'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/leasing"
          
      - name: Send Telegram notification on success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode=Markdown \
          -d text="✅ *Деплой успешен*\nRepo: `${GITHUB_REPOSITORY}`\nBranch: `${GITHUB_REF_NAME}`\nCommit: `${GITHUB_SHA}`\nVersion: `${{ steps.bump_version.outputs.new_version }}`\nActor: `${GITHUB_ACTOR}`"

      - name: Send Telegram notification on failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode=Markdown \
          -d text="❌ *Деплой провален*\nRepo: `${GITHUB_REPOSITORY}`\nBranch: `${GITHUB_REF_NAME}`\nCommit: `${GITHUB_SHA}`\nVersion: `${{ steps.bump_version.outputs.new_version }}`\nActor: `${GITHUB_ACTOR}`"