name: Deploy Leasing to leasing.sergeivbo.ru

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bump version and push tag
        id: bump_version
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: 'v'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/leasing"

      - name: Send Telegram notification on success
        if: success()
        run: |
          VERSION=${{ steps.bump_version.outputs.new_version }}
          AUTHOR=$(git log -2 --pretty=format:'%an' | tail -1)
          COMMIT_MESSAGE=$(git log -2 --pretty=format:'%s' | tail -1)
          COMMIT_SHA=$(git log -2 --pretty=format:'%h' | tail -1)
          REPO=${GITHUB_REPOSITORY}
          BRANCH=${GITHUB_REF##*/}
          ACTOR=${GITHUB_ACTOR}

          MESSAGE="✅ *Деплой успешен*%0A%0ARepo: $REPO%0ABranch: $BRANCH%0ACommit: $COMMIT_SHA%0ACommit Message: $COMMIT_MESSAGE%0AVersion: $VERSION%0AActor: $ACTOR%0ACommit Author: $AUTHOR"

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="$MESSAGE"

      - name: Send Telegram notification on failure
        if: failure()
        run: |
          VERSION=${{ steps.bump_version.outputs.new_version }}
          AUTHOR=$(git log -2 --pretty=format:'%an' | tail -1)
          COMMIT_MESSAGE=$(git log -2 --pretty=format:'%s' | tail -1)
          COMMIT_SHA=$(git log -2 --pretty=format:'%h' | tail -1)
          REPO=${GITHUB_REPOSITORY}
          BRANCH=${GITHUB_REF##*/}
          ACTOR=${GITHUB_ACTOR}

          MESSAGE="❌ *Деплой провален*%0A%0ARepo: $REPO%0ABranch: $BRANCH%0ACommit: $COMMIT_SHA%0ACommit Message: $COMMIT_MESSAGE%0AVersion: $VERSION%0AActor: $ACTOR%0ACommit Author: $AUTHOR"

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="$MESSAGE"