name: Deploy Leasing to leasing.sergeivbo.ru

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bump version and push tag
        id: bump_version
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: 'v'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/leasing"

      - name: Send Telegram notification on success
        if: success()
        run: |
          VERSION=${{ steps.bump_version.outputs.new_version }}
          AUTHOR=$(git log -1 --pretty=format:'%an')
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode=Markdown \
          -d text='✅ *Деплой успешен*
Repo: '"${GITHUB_REPOSITORY}"'
Branch: '"${GITHUB_REF_NAME}"'
Commit: '"${GITHUB_SHA}"'
Version: '"${VERSION}"'
Actor: '"${GITHUB_ACTOR}"'
Commit Author: '"${AUTHOR}"''

      - name: Send Telegram notification on failure
        if: failure()
        run: |
          VERSION=${{ steps.bump_version.outputs.new_version }}
          AUTHOR=$(git log -1 --pretty=format:'%an')
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode=Markdown \
          -d text='❌ *Деплой провален*
Repo: '"${GITHUB_REPOSITORY}"'
Branch: '"${GITHUB_REF_NAME}"'
Commit: '"${GITHUB_SHA}"'
Version: '"${VERSION}"'
Actor: '"${GITHUB_ACTOR}"'
Commit Author: '"${AUTHOR}"''
